### PR TITLE
meta: drop the "the" and add graphics

### LINKED ISSUE #86: Enable link preview for the book
Enable link preview for the Foundry Book (https://onbjerg.github.io/foundry-book/) to be show on social media

I will make a thumbnail - lmk!

### PR DESCRIPTION
**Pull request by ZeroEkkusu**
### Compress `foundry-banner.png`

From 3.6 MB to 730 KB, to improve UX.

### Add custom favicon

**Edit**: Made a new one

lfp
dfp

### Enable link preview when sharing

... And make a thumbnail.

cardv2
Even though some metas are Twitter specific, it works in other apps as well.
cardv2other
Here's another experimental one (not included). **Feedback wanted.**
cardv1

### Drop the `The`

Just `Foundry Book`. It's cleaner.

thethe

Closes #86

### CODE REVIEW

**Comment by onbjerg** [comment]
cc @gakonst for thoughts on banner

**Comment by gakonst** [comment]
I am OK with dropping the "The", not sure yet on the anime branding, +1 on compressing the banner. Maybe let's use the banner as the preview image?

**Comment by ZeroEkkusu** [comment]
Sure thing!

**Comment by onbjerg** [comment]
Bump on this @ZeroEkkusu :smile:

**Review by gakonst — APPROVED** [review]

**Pull request merged**
