### PR TITLE
small fixes to solmate nft tutorial

### PR DESCRIPTION
**Pull request by dmfxyz**
I am writing a Docker tutorial that builds off the awesome solmate tutorial currently in the foundry book. While writing it, I noticed a few minor bugs in the NFT tutorial:

1. Does not explicitly instruct user to install openzeppelin dependencies
2. The "Basic NFT" won't actually compile because it does not implement the `tokenURI` function from Rari's ERC721 abstract contract.

I just made a couple edits to address these small "bugs".

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
This looks great - thank you. Any chance I could ask you to fix the remaining issues in #133 as well? If not, no big deal!

**Comment by onbjerg** [comment]
@all-contributors add @dmfxyz for maintenance

**Comment by dmfxyz** [comment]
@onbjerg Yeah, no problem. I have to get it all in a working state for the docker tutorial anyway :)

I think we should add a disclaimer with the tutorials. Something like "This tutorial is for illustrative purposes only and provided on an as-is basis. The tutorial is not audited nor fully tested. No code in this book should be used in a production environment without proper testing and auditing."

Thoughts? Foundry is maintained by a number of leaders in this space, so I could see people coming here and just copy pasting...

**Comment by dmfxyz** [comment]
@onbjerg I've removed the OZ PullPayments (it's overkill for this tutorial) and replaced it with a simple onlyOwner withdrawal method. Added tests for the withdrawal. Also added disclaimer. I think this should address everything in #133 and be good to merge, and then I can build the docker tutorial off of that.

**Comment by onbjerg** [comment]
Thank you!!!

**Pull request merged**
