### PR TITLE
docs: add help for finding compiler commit

### PR DESCRIPTION
**Pull request by devtooligan**
This adds some additional text and trouble shooting tips around finding the `compiler-version` commit argument to pass to `forge verify`

### CODE REVIEW

**Comment by devtooligan** [comment]
@onbjerg can u pls help me understand more about this failing test or where I can find it?

**Comment by ZeroEkkusu** [comment]
> @onbjerg can u pls help me understand more about this failing test or where I can find it?

Ser, just add `text` or `ignore`.

``````
```ignore
solc, the solidity compiler commandline interface
Version: 0.8.12+commit.f00d7308.Darwin.appleclang
```
``````

**Comment by devtooligan** [comment]
Thanks @ZeroEkkusu!!  Do you know what causes that?  Is it a linter?  Or some new style guideline?

I feel like I've done a lot of code blocks in md and never been forced to enter the language before

**Comment by mds1** [comment]
@devtooligan see here 🙂 https://rust-lang.github.io/mdBook/cli/test.html

**Comment by devtooligan** [comment]
@mds1 v interesting thanks ser

**Comment by onbjerg** [comment]
Thank you for this! :smile: And yes, the lint is an mdbook-specific thing. Basically, mdbook was built for Rust projects first, so it will actually try to validate some of the codeblocks to see that they work

**Comment by onbjerg** [comment]
@all-contributors add @devtooligan for docs

**Pull request merged**
